In [26]:
import numpy as np

In [27]:
temps = np.array([[30,32,31,29,28,27,26],
                  [22,21,23,24,25,26,24],
                  [15,17,16,18,19,20,21]])

In [28]:
temps

array([[30, 32, 31, 29, 28, 27, 26],
       [22, 21, 23, 24, 25, 26, 24],
       [15, 17, 16, 18, 19, 20, 21]])

In [29]:
temps.shape

(3, 7)

In [45]:
cityA_max =temps[0].max()
cityA_max

np.int64(32)

In [31]:
Days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturaday','Sunday']
Days

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturaday', 'Sunday']

In [32]:
city_temp = temps.argmax(axis=1)
city_temp

array([1, 5, 6])

In [33]:
day_temp =temps.argmax(axis=0)
day_temp

array([0, 0, 0, 0, 0, 0, 0])

In [42]:
for i, day in enumerate(Days):
    print(f" {day}: Temperature:{temps[day_temp[i],i]}")
for i in range(len(temps)):
    print("---------------------------")
    print(f" High_Temprature_Days: {Days[city_temp[i]]}") 
    print("---------------------------")


 Monday: Temperature:30
 Tuesday: Temperature:32
 Wednesday: Temperature:31
 Thursday: Temperature:29
 Friday: Temperature:28
 Saturaday: Temperature:27
 Sunday: Temperature:26
---------------------------
 High_Temprature_Days: Tuesday
---------------------------
---------------------------
 High_Temprature_Days: Saturaday
---------------------------
---------------------------
 High_Temprature_Days: Sunday
---------------------------
city_A temperature is higher


In [43]:
city_A = temps[0]
city_B = temps[1]
city_A , city_B

(array([30, 32, 31, 29, 28, 27, 26]), array([22, 21, 23, 24, 25, 26, 24]))

In [44]:
if temps[0].max() > temps[1].max():
    print("city_A temperature is higher")
else:
    print('city_B temperature is higher')


city_A temperature is higher
