In [1]:
import numpy as np

In [2]:
Student_Data = {"St_1":{'Math':85,'Urdu':70,'Sindhi':40,'Chemistry':90,'Physics':60},             
                'St_2':{'Math':85,'Urdu':75,'Sindhi':40,'Chemistry':90,'Physics':60},
                'St_3':{'Math':80,'Urdu':70,'Sindhi':95,'Chemistry':90,'Physics':60},
                'St_4':{'Math':80,'Urdu':70,'Sindhi':50,'Chemistry':85,'Physics':60},
                'St_5':{'Math':80,'Urdu':75,'Sindhi':40,'Chemistry':90,'Physics':60}}

In [3]:
student_ID = list(Student_Data.keys())

In [4]:
student_ID

['St_1', 'St_2', 'St_3', 'St_4', 'St_5']

In [5]:
student = list(Student_Data.values())
student

[{'Math': 85, 'Urdu': 70, 'Sindhi': 40, 'Chemistry': 90, 'Physics': 60},
 {'Math': 85, 'Urdu': 75, 'Sindhi': 40, 'Chemistry': 90, 'Physics': 60},
 {'Math': 80, 'Urdu': 70, 'Sindhi': 95, 'Chemistry': 90, 'Physics': 60},
 {'Math': 80, 'Urdu': 70, 'Sindhi': 50, 'Chemistry': 85, 'Physics': 60},
 {'Math': 80, 'Urdu': 75, 'Sindhi': 40, 'Chemistry': 90, 'Physics': 60}]

In [6]:
s = student[0]

In [7]:
subjects = list(s.keys())

In [8]:
subjects

['Math', 'Urdu', 'Sindhi', 'Chemistry', 'Physics']

In [9]:
student1 = [list(marks.values()) for marks in Student_Data.values()]

In [10]:
student1

[[85, 70, 40, 90, 60],
 [85, 75, 40, 90, 60],
 [80, 70, 95, 90, 60],
 [80, 70, 50, 85, 60],
 [80, 75, 40, 90, 60]]

In [11]:
student1 = np.array(student1)

In [12]:
max_subjects = student1.argmax(axis=0)
min_subjects = student1.argmin(axis=0)
print(max_subjects , min_subjects)

[0 1 2 0 0] [2 0 0 3 0]


In [13]:
max_student = student1.argmax(axis=1)
min_student = student1.argmin(axis=1)
print(max_student , min_student)

[3 3 2 3 3] [2 2 4 2 2]


In [19]:
for i, (ID,subject) in enumerate(zip(student_ID,subjects)):
    print(f"{ID}, {subject}: max_marks:{student1[max_subjects[i],i]}, min_marks:{student1[min_subjects[i],i]}")
print("----------------------------------------")
for loc, (student) in enumerate(student1):
    print(f" student no:{loc+1}\nmax_marks: {student[max_student[loc]]}, min_marks:{student[min_student[loc]]}\nsubject: {subjects[max_student[loc]]},{subjects[min_student[loc]]}")
    print("____________________")
print("----------------------------------------")

St_1, Math: max_marks:85, min_marks:80
St_2, Urdu: max_marks:75, min_marks:70
St_3, Sindhi: max_marks:95, min_marks:40
St_4, Chemistry: max_marks:90, min_marks:85
St_5, Physics: max_marks:60, min_marks:60
----------------------------------------
 student no:1
max_marks: 90, min_marks:40
subject: Chemistry,Sindhi
____________________
 student no:2
max_marks: 90, min_marks:40
subject: Chemistry,Sindhi
____________________
 student no:3
max_marks: 95, min_marks:60
subject: Sindhi,Physics
____________________
 student no:4
max_marks: 85, min_marks:50
subject: Chemistry,Sindhi
____________________
 student no:5
max_marks: 90, min_marks:40
subject: Chemistry,Sindhi
____________________
----------------------------------------


In [15]:
student_total = student1.sum(axis=1)
student_total

array([345, 350, 395, 345, 345])

In [16]:
rank_index = student_total.argsort()[::-1]
rank_index

array([2, 1, 4, 3, 0])

In [17]:
for loc, (ID) in enumerate(student_ID):
    print(f"{ID}: Rank_{loc+1}, Total :{student_total[rank_index[loc]]}")

St_1: Rank_1, Total :395
St_2: Rank_2, Total :350
St_3: Rank_3, Total :345
St_4: Rank_4, Total :345
St_5: Rank_5, Total :345
